In [ ]:
'''
【课程2.2】  Pandas数据结构Series：基本概念及创建

"一维数组"Serise

'''

In [1]:
# 导入numpy、pandas模块
import numpy as np
import pandas as pd

In [2]:
# Series 数据结构
# Series 是带有标签的一维数组，可以保存任何数据类型（整数，字符串，浮点数，Python对象等）,轴标签统称为索引

ar = np.random.rand(5)
s = pd.Series(ar)
print(ar)
print(s)
print(type(ar), type(s))
print('-----------')
print(s.index, list(s.index))
print(s.values, type(s.values))
# .index查看series索引，类型为rangeindex
# .values查看series值，类型是ndarray

# 核心：series相比于ndarray，是一个自带索引index的数组 → 一维数组 + 对应索引
# 所以当只看series的值的时候，就是一个ndarray
# series和ndarray较相似，索引切片功能差别不大
# series和dict相比，series更像一个有顺序的字典（dict本身不存在顺序），其索引原理与字典相似（一个用key，一个用index）

s2 = pd.Series(ar, index=list('abcde'))   # 索引index不一定为数字，可以是字母
print(s2)

[0.78087401 0.73607659 0.55375446 0.17752614 0.74582616]
0    0.780874
1    0.736077
2    0.553754
3    0.177526
4    0.745826
dtype: float64
<class 'numpy.ndarray'> <class 'pandas.core.series.Series'>
-----------
RangeIndex(start=0, stop=5, step=1) [0, 1, 2, 3, 4]
[0.78087401 0.73607659 0.55375446 0.17752614 0.74582616] <class 'numpy.ndarray'>
a    0.780874
b    0.736077
c    0.553754
d    0.177526
e    0.745826
dtype: float64


In [3]:
# Series 创建方法一：由字典创建，字典的key就是index，values就是values

dic = {'a':1, 'b':2, 'c':3, 'd':'hello', 5:20}
s = pd.Series(dic)
print(s)

a        1
b        2
c        3
d    hello
5       20
dtype: object


In [5]:
# Series 创建方法二：由数组创建(一维数组)

arr = np.random.rand(10,)*100
print(arr)
ss = pd.Series(arr, index=list('abcdefghij'), dtype=np.int)
print(ss)

# 默认index是从0开始，步长为1的数字
# index参数：设置index，长度保持一致
# dtype参数：设置数值类型

[63.6564218   7.22909602 76.30702407 18.36791927 31.07190755 99.63579016
 45.13901961 75.9642771  32.49118264 31.47198809]
a    63.656422
b     7.229096
c    76.307024
d    18.367919
e    31.071908
f    99.635790
g    45.139020
h    75.964277
i    32.491183
j    31.471988
dtype: float64


In [8]:
# Series 创建方法三：由标量创建

s = pd.Series(126, index = range(10))
print(s)
# 如果data是标量值，则必须提供索引。该值会重复，来匹配索引的长度

0    126
1    126
2    126
3    126
4    126
5    126
6    126
7    126
8    126
9    126
dtype: int64


In [6]:
# Series 名称属性：name

s1 = pd.Series(np.random.randn(5))
print(s1)
print('-----')
s2 = pd.Series(np.random.randn(5),name = 'test')
print(s2)
print(s1.name, s2.name,type(s2.name))
# name为Series的一个参数，创建一个数组的 名称
# .name方法：输出数组的名称，输出格式为str，如果没用定义输出名称，输出为None

s3 = s2.rename('hehehe')
print(s3)
print(s3.name, s2.name)
# .rename()重命名一个数组的名称，并且新指向一个数组，原数组不变

0   -0.680570
1   -0.874072
2   -1.713062
3   -0.100428
4    0.114255
dtype: float64
-----
0   -0.344364
1   -0.144433
2    0.772970
3    0.591344
4    1.075392
Name: test, dtype: float64
None test <class 'str'>
0   -0.344364
1   -0.144433
2    0.772970
3    0.591344
4    1.075392
Name: hehehe, dtype: float64
hehehe test


In [ ]:
'''
【课程2.3】  Pandas数据结构Series：索引

位置下标 / 标签索引 / 切片索引 / 布尔型索引

'''

In [5]:
# 位置下标，类似序列

s = pd.Series(np.random.rand(10))
print(s)
print(s[5],type(s[6]),s[7].dtype)
# 位置下标从0开始

0    0.936244
1    0.488159
2    0.969322
3    0.122498
4    0.347878
5    0.633508
6    0.537084
7    0.769413
8    0.722966
9    0.380726
dtype: float64
0.6335081178183238 <class 'numpy.float64'> float64


In [10]:
# 标签索引

s = pd.Series(np.random.rand(5), index = ['a','b','c','d','e'])
print(s)
print(s['a'],type(s['a']),s['a'].dtype)
# 方法类似下标索引，用[]表示，内写上index，注意index是字符串

print(s[['c','a','b']])  # 同时选取多个标签的时候,可以不按顺序
sci = s[['a','b','e']]
print(sci,type(sci))
# 如果需要选择多个标签的值，用[[]]来表示（相当于[]中包含一个列表）
# 多标签索引结果是新的数组

a    0.227128
b    0.728541
c    0.904424
d    0.837876
e    0.453048
dtype: float64
0.22712756824129432 <class 'numpy.float64'> float64
c    0.904424
a    0.227128
b    0.728541
dtype: float64
a    0.227128
b    0.728541
e    0.453048
dtype: float64 <class 'pandas.core.series.Series'>


In [18]:
# 切片索引

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5),index=['a','b','c','d','e'])
print(s1, '\n--------')
print(s2, '\n--------')
print(s1[1:4], s1[4])   # 下标
print(s2['a':'c'], s2['c'])   # 标签(末端包含)
print(s2[0:3], s2[3])
print('-----')
# 注意：用标签索引index做切片是末端包含

print(s2[:-1])
print(s2[::2])
# 下标索引做切片，和list写法一样

0    0.991787
1    0.081731
2    0.365219
3    0.909600
4    0.770595
dtype: float64 
--------
a    0.255550
b    0.106897
c    0.748090
d    0.890867
e    0.663743
dtype: float64 
--------
1    0.081731
2    0.365219
3    0.909600
dtype: float64 0.7705951301209877
a    0.255550
b    0.106897
c    0.748090
dtype: float64 0.748090356710721
a    0.255550
b    0.106897
c    0.748090
dtype: float64 0.8908674757739627
-----
a    0.255550
b    0.106897
c    0.748090
d    0.890867
dtype: float64
a    0.255550
c    0.748090
e    0.663743
dtype: float64


In [23]:
# 布尔型索引

s = pd.Series(np.random.rand(3)*100)
s[4] = None  # 添加一个空值
s[5] = np.nan   # 添加空值也可以这样写
print(s)
bs1 = s > 50
bs2 = s.isnull()
bs3 = s.notnull()
print(bs1, type(bs1), bs1.dtype, '\n--------')
print(bs2, type(bs2), bs2.dtype, '\n--------')
print(bs3, type(bs3), bs3.dtype, '\n--------')
print('------------------------------')
# 数组做判断之后，返回的是一个由布尔值组成的新的数组
# .isnull() / .notnull() 判断是否为空值 (None代表空值，NaN代表有问题的数值，两个都会识别为空值)

print(s[s > 50])
print(s[bs3])
# 布尔型索引方法：用[判断条件]表示，其中判断条件可以是 一个语句，或者是 一个布尔型数组！

0    92.2965
1    72.1777
2    5.77241
4       None
5        NaN
dtype: object
0     True
1     True
2    False
4    False
5    False
dtype: bool <class 'pandas.core.series.Series'> bool 
--------
0    False
1    False
2    False
4     True
5     True
dtype: bool <class 'pandas.core.series.Series'> bool 
--------
0     True
1     True
2     True
4    False
5    False
dtype: bool <class 'pandas.core.series.Series'> bool 
--------
------------------------------
0    92.2965
1    72.1777
dtype: object
0    92.2965
1    72.1777
2    5.77241
dtype: object


In [ ]:
'''
【课程2.4】  Pandas数据结构Series：基本技巧

数据查看 / 重新索引 / 对齐 / 添加、修改、删除值

'''

In [24]:
# 数据查看

s = pd.Series(np.random.rand(15))
print(s.head())
print(s.tail())
# .head()查看头部数据
# .tail()查看尾部数据
# 默认查看5条

0    0.302604
1    0.907364
2    0.766996
3    0.067825
4    0.762444
dtype: float64
10    0.916022
11    0.214472
12    0.182211
13    0.564559
14    0.222518
dtype: float64


In [33]:
# 重新索引 reindex
# .reindex将会根据索引重新排序，如果当前索引不存在，则引入缺失值

s = pd.Series(np.random.rand(5), index=list('abcde'))
print(s)
print('--------')
s1 = s.reindex(['zz','yy','xx','c','a'])
print(s1)
print(s.reindex(['zz','yy','xx','c','a']))
print('--------')

s2 = s.reindex(['zz','yy','xx','c','a','cccccc'], fill_value=0)
print(s2)
# fill_value参数：填充缺失值的值

a    0.402655
b    0.699154
c    0.308334
d    0.787954
e    0.560302
dtype: float64
--------
zz         NaN
yy         NaN
xx         NaN
c     0.308334
a     0.402655
dtype: float64
zz         NaN
yy         NaN
xx         NaN
c     0.308334
a     0.402655
dtype: float64
--------
zz        0.000000
yy        0.000000
xx        0.000000
c         0.308334
a         0.402655
cccccc    0.000000
dtype: float64


In [36]:
# Series对齐

s1 = pd.Series(np.random.rand(3), index = ['Jack','Marry','Tom'])
s2 = pd.Series(np.random.rand(3), index = ['Wang','Jack','Marry'])
print(s1)
print('--------')
print(s2)
print('--------')
print(s1+s2)
# Series 和 ndarray 之间的主要区别是，Series 上的操作会根据标签自动对齐
# index顺序不会影响数值计算，以标签来计算
# 空值和任何值计算结果扔为空值

Jack     0.231432
Marry    0.747641
Tom      0.647475
dtype: float64
--------
Wang     0.025933
Jack     0.879019
Marry    0.979609
dtype: float64
--------
Jack     1.110451
Marry    1.727250
Tom           NaN
Wang          NaN
dtype: float64


In [37]:
# 删除：.drop

s = pd.Series(np.random.rand(5), index = list('ngjur'))
print(s)
s1 = s.drop('n')
s2 = s.drop(['g','j'])
print(s1)
print('--------')
print(s2)
print('--------')
print(s)
# drop 删除元素之后返回副本(inplace=False)

n    0.018801
g    0.270495
j    0.633204
u    0.879861
r    0.895924
dtype: float64
g    0.270495
j    0.633204
u    0.879861
r    0.895924
dtype: float64
--------
n    0.018801
u    0.879861
r    0.895924
dtype: float64
--------
n    0.018801
g    0.270495
j    0.633204
u    0.879861
r    0.895924
dtype: float64


In [3]:
# 添加

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = list('ngjur'))
print(s1)
print('--------')
print(s2)
print('--------')
s1[5] = 100
s2['a'] = 100
print(s1)
print('--------')
print(s2)
print('-----')
# 直接通过下标索引/标签index添加值

s3 = s1.append(s2)
print(s3)
print('--------')
print(s1)
# 通过.append方法，直接添加一个数组
# .append方法生成一个新的数组，不改变之前的数组

0    0.282983
1    0.094869
2    0.476947
3    0.873530
4    0.313112
dtype: float64
--------
n    0.780867
g    0.179253
j    0.598774
u    0.562769
r    0.282016
dtype: float64
--------
0      0.282983
1      0.094869
2      0.476947
3      0.873530
4      0.313112
5    100.000000
dtype: float64
--------
n      0.780867
g      0.179253
j      0.598774
u      0.562769
r      0.282016
a    100.000000
dtype: float64
-----
0      0.282983
1      0.094869
2      0.476947
3      0.873530
4      0.313112
5    100.000000
n      0.780867
g      0.179253
j      0.598774
u      0.562769
r      0.282016
a    100.000000
dtype: float64
--------
0      0.282983
1      0.094869
2      0.476947
3      0.873530
4      0.313112
5    100.000000
dtype: float64


In [4]:
# 修改

s = pd.Series(np.random.rand(3), index = ['a','b','c'])
print(s)
print('--------')
s['a'] = 100
s[['b','c']] = 200
print(s)
# 通过索引直接修改，类似序列

a    0.597702
b    0.563281
c    0.028927
dtype: float64
--------
a    100.0
b    200.0
c    200.0
dtype: float64


In [ ]:
'''
【课程2.5】  Pandas数据结构Dataframe：基本概念及创建

"二维数组"Dataframe：是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。

Dataframe中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。

'''

In [9]:
# Dataframe 数据结构
# Dataframe是一个表格型的数据结构，“带有标签的二维数组”。
# Dataframe带有index（行标签）和columns（列标签）

data = {'name':['Jack','Tom','Mary'],
        'age':[18,19,20],
       'gender':['m','m','w']}
frame = pd.DataFrame(data)
print(frame)  
print(type(frame))
print(frame.index,'\n该数据类型为：',type(frame.index))
print(frame.columns,'\n该数据类型为：',type(frame.columns))
print(frame.values,'\n该数据类型为：',type(frame.values))
# 查看数据，数据类型为dataframe
# .index查看行标签
# .columns查看列标签
# .values查看值，数据类型为ndarray

   name  age gender
0  Jack   18      m
1   Tom   19      m
2  Mary   20      w
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 
该数据类型为： <class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'gender'], dtype='object') 
该数据类型为： <class 'pandas.core.indexes.base.Index'>
[['Jack' 18 'm']
 ['Tom' 19 'm']
 ['Mary' 20 'w']] 
该数据类型为： <class 'numpy.ndarray'>


### Pandas数据结构Dataframe的创建:
- Dataframe 创建方法一：由数组/list组成的字典
- Dataframe 创建方法二：由Series组成的字典
- Dataframe 创建方法三：通过二维数组直接创建（最方便快捷的方法）
- Dataframe 创建方法四：由字典组成的列表
- Dataframe 创建方法五：由字典组成的字典

In [16]:
# Dataframe 创建方法一：由数组/list组成的字典
# 创建方法:pandas.Dataframe()

data1 = {'a':[1,2,3],
        'b':[3,4,5],
        'c':[5,6,7]}
data2 = {'one':np.random.rand(3),
        'two':np.random.rand(3)}
print(data1)
print(data2)
print('------')
df1 = pd.DataFrame(data1, index=['A','B','C'])
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
print('----------------')
# 由数组/list组成的字典 创建Dataframe，columns为字典key，index为默认数字标签
# 字典的值的长度必须保持一致！

df1 = pd.DataFrame(data1, columns = ['b','c','a','d'])
print(df1)
df1 = pd.DataFrame(data1, columns = ['b','c'])
print(df1)
# columns参数：可以重新指定列的顺序，格式为list，如果现有数据中没有该列（比如'd'），则产生NaN值
# 如果columns重新指定时候，列的数量可以少于原数据

df2 = pd.DataFrame(data2, index = ['f1','f2','f3'])  # 这里如果尝试  index = ['f1','f2','f3','f4'] 会怎么样？
print(df2)
# index参数：重新定义index，格式为list，长度必须保持一致

{'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
{'one': array([0.73280108, 0.94674823, 0.50065813]), 'two': array([0.43371633, 0.23629416, 0.71345722])}
------
   a  b  c
A  1  3  5
B  2  4  6
C  3  5  7
        one       two
0  0.732801  0.433716
1  0.946748  0.236294
2  0.500658  0.713457
----------------
   b  c  a    d
0  3  5  1  NaN
1  4  6  2  NaN
2  5  7  3  NaN
   b  c
0  3  5
1  4  6
2  5  7
         one       two
f1  0.732801  0.433716
f2  0.946748  0.236294
f3  0.500658  0.713457


In [19]:
# Dataframe 创建方法二：由Series组成的字典

data1 = {'one':pd.Series(np.random.rand(2)),
        'two':pd.Series(np.random.rand(3))}  # 没有设置index的Series
data2 = {'one':pd.Series(np.random.rand(2), index = ['a','b']),
        'two':pd.Series(np.random.rand(3),index = ['a','b','c'])}  # 设置了index的Series
print(data1)
print('------')
print(data2)
print('----------------')
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print('------')
print(df2)
# 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
# Series可以长度不一样，生成的Dataframe会出现NaN值

{'one': 0    0.900319
1    0.171676
dtype: float64, 'two': 0    0.846832
1    0.119898
2    0.807187
dtype: float64}
------
{'one': a    0.150305
b    0.132374
dtype: float64, 'two': a    0.115882
b    0.189449
c    0.689907
dtype: float64}
----------------
        one       two
0  0.900319  0.846832
1  0.171676  0.119898
2       NaN  0.807187
------
        one       two
a  0.150305  0.115882
b  0.132374  0.189449
c       NaN  0.689907


In [24]:
# Dataframe 创建方法三：通过二维数组直接创建（最方便快捷的方法）

ar = np.random.rand(9).reshape(3,3)
print(ar)
print('--------------')
df1 = pd.DataFrame(ar)
print(df1)
print('------')
df2 = pd.DataFrame(ar, index=list('abc'), columns=['one','two','three'])
df3 = pd.DataFrame(ar,
                  columns=['车型','原厂地','品牌'],
                  index=['Audi','BMW','Benz'])
print(df2)
print('------')
print(df3)
# 通过二维数组直接创建Dataframe，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
# index和colunms指定长度与原数组保持一致

[[0.96580581 0.84782916 0.32916836]
 [0.44329933 0.33975199 0.1520495 ]
 [0.85867287 0.97092353 0.57813354]]
--------------
          0         1         2
0  0.965806  0.847829  0.329168
1  0.443299  0.339752  0.152050
2  0.858673  0.970924  0.578134
------
        one       two     three
a  0.965806  0.847829  0.329168
b  0.443299  0.339752  0.152050
c  0.858673  0.970924  0.578134
------
            车型       原厂地        品牌
Audi  0.965806  0.847829  0.329168
BMW   0.443299  0.339752  0.152050
Benz  0.858673  0.970924  0.578134


In [26]:
# Dataframe 创建方法四：由字典组成的列表

data = [{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]   # 一个字典代表一行数据
print(data)
print('------')
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index = ['a','b'])
df3 = pd.DataFrame(data, columns = ['one','two'])
print(df1, '\n------')
print(df2, '\n------')
print(df3, '\n------')
# 由字典组成的列表创建Dataframe，columns为字典的key，index不做指定则为默认数组标签
# colunms和index参数分别重新指定相应列及行标签

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
------
   one  three  two
0    1    NaN    2
1    5   20.0   10 
------
   one  three  two
a    1    NaN    2
b    5   20.0   10 
------
   one  two
0    1    2
1    5   10 
------


In [28]:
# Dataframe 创建方法五：由字典组成的字典

data = {'Jack':{'math':90,'english':89,'art':78},
       'Marry':{'math':82,'english':95,'art':92},
       'Tom':{'math':78,'english':67}}
df1 = pd.DataFrame(data)               # 字典里面嵌套的字典，外层的key为列标签，里面的key指的每一个index （同下面一句话）
print(df1)
print('------')
# 由字典组成的字典创建Dataframe，columns为字典的key，index为子字典的key

df2 = pd.DataFrame(data, columns = ['Jack','Tom','Bob'])
df3 = pd.DataFrame(data, index = ['a','b','c'])
print(df2, '\n------')
print(df3, '\n------')
# columns参数可以增加和减少现有列，如出现新的列，值为NaN
# index在这里和之前不同，并不能改变原有index，如果指向新的标签，值为NaN （非常重要！）

         Jack  Marry   Tom
art        78     92   NaN
english    89     95  67.0
math       90     82  78.0
------
         Jack   Tom  Bob
art        78   NaN  NaN
english    89  67.0  NaN
math       90  78.0  NaN 
------
   Jack  Marry  Tom
a   NaN    NaN  NaN
b   NaN    NaN  NaN
c   NaN    NaN  NaN 
------


In [ ]:
'''
【课程2.6】  Pandas数据结构Dataframe：索引

Dataframe既有行索引也有列索引，可以被看做由Series组成的字典（共用一个索引）

选择列 / 选择行 / 切片 / 布尔判断

'''

In [ ]:
# 选择行与列



In [ ]:
# df[] - 选择列
# 一般用于选择列，也可以选择行



In [ ]:
# df.loc[] - 按index选择行



In [ ]:
# df.iloc[] - 按照整数位置（从轴的0到length-1）选择行
# 类似list的索引，其顺序就是dataframe的整数位置，从0开始计



In [ ]:
# 布尔型索引
# 和Series原理相同



In [ ]:
# 多重索引：比如同时索引行和列
# 先选择列再选择行 —— 相当于对于一个数据，先筛选字段，再选择数据量



In [ ]:
'''
【课程2.7】  Pandas数据结构Dataframe：基本技巧

数据查看、转置 / 添加、修改、删除值 / 对齐 / 排序

'''