In [ ]:
'''
【课程1.2】  Numpy基础数据结构

NumPy数组是一个多维数组对象，称为ndarray。其由两部分组成：
① 实际的数据
② 描述这些数据的元数据

'''

In [18]:
# 多维数组ndarray

import numpy as np

ar = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(ar)
print(ar.ndim)   # 数组的维度个数，轴
print(ar.shape)  # 数组的维度，几行几列
print(ar.size)   # 数组的元素个数
print(type(ar), ar.dtype)  # 数组的类型，和数组里面元素的类型
print(ar.itemsize)   # 每个元素字节大小
print(ar.data)
ar

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
2
(2, 6)
12
<class 'numpy.ndarray'> int32
4


array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [12]:
# 多维数组演示 维度的个数（轴数） ar.ndim

# 一维数组
ar_1 = np.array([1,2,3,4,5,6])
print(ar_1, '\n',ar_1.ndim)
print('-'*80)

# 二维数组 由多个一维数组组成
ar_2 = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(ar_2, '\n',ar_2.ndim)
print('-'*80)

#  三维数组 由多个二维数组组成
ar_3 = np.array([[[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8]],[[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8]]])
print(ar_3, '\n',ar_3.ndim)
print('-'*80)

# 四维数组 由多个三维数组组成，以此内推…

[1 2 3 4 5 6] 
 1
--------------------------------------------------------------------------------
[[1 2 3 4 5 6]
 [2 3 4 5 6 7]] 
 2
--------------------------------------------------------------------------------
[[[1 2 3 4 5 6]
  [2 3 4 5 6 7]
  [3 4 5 6 7 8]]

 [[1 2 3 4 5 6]
  [2 3 4 5 6 7]
  [3 4 5 6 7 8]]] 
 3
--------------------------------------------------------------------------------


In [32]:
# 创建数组：array()函数，括号内可以是列表、元祖、数组、生成器等

ar1 = np.array(range(10))   # 直接通过生成器range去创建
print(ar1)

ar2 = np.arange(10)   # 创建数组：arange()，类似range()，在给定间隔内返回均匀间隔的值。
print(ar2)

ar3 = np.array([1,2,3,4,5,6])  # 使用列表创建
print(ar3)

print('--------------------------------------------------------')
ar4 = np.array([[1,2,3,4,5],[2,3,4,5,6]])  # 使用嵌套的列表
ar5 = np.array([[1,2,3,4,5],['a','b','c','d','e']])    # 元素个数相同时，是二维数组，但数值类型改变
ar6 = np.array([[1,2,3,4,5],['a','b','c']])    # 元素个数不相同时，变成一维数组
print(ar4, ar4.ndim, ar4.dtype)
print(ar5, ar4.ndim, ar5.dtype)
print(ar6, ar6.ndim, ar6.dtype)
print('--------------------------------------------------------')

ar1, ar2, ar3, ar4

print(np.random.rand(10).reshape(2,5))   # 以后更多使用该种方法

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6]
--------------------------------------------------------
[[1 2 3 4 5]
 [2 3 4 5 6]] 2 int32
[['1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e']] 2 <U11
[list([1, 2, 3, 4, 5]) list(['a', 'b', 'c'])] 1 object
--------------------------------------------------------
[[0.69434762 0.19600356 0.78168196 0.18383448 0.07031041]
 [0.91712702 0.19706813 0.70006688 0.76954788 0.75165578]]


In [44]:
# 创建数组：linspace():返回在间隔[开始，停止]上计算的num个均匀间隔的样本。

print(np.linspace(10,20,num=21))
print(np.linspace(10,20,num=21,endpoint=False))
print(np.linspace(10,20,num=20,endpoint=False))
print(np.linspace(10,20,num=21,retstep=True))

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]
[10.         10.47619048 10.95238095 11.42857143 11.9047619  12.38095238
 12.85714286 13.33333333 13.80952381 14.28571429 14.76190476 15.23809524
 15.71428571 16.19047619 16.66666667 17.14285714 17.61904762 18.0952381
 18.57142857 19.04761905 19.52380952]
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]
(array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ]), 0.5)


In [53]:
# 创建数组：zeros()/zeros_like()/ones()/ones_like()

print(np.zeros(10))
print(np.zeros((2,5)))
print(np.zeros((2,5),dtype=int))

print('--------------------------------------------------------')
ar = np.array([list(range(10)),list(range(10,20))])
print(ar)
print(np.zeros_like(ar,dtype=float))
print('--------------------------------------------------------')

print(np.ones_like(ar))
ar7 = np.ones(9)
ar8 = np.ones((3,5))
ar9 = np.ones((2,3,4))   # shape，2个3行4列的2维数组组成的三维数组
print(ar7)
print(ar8)
print(ar9)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
--------------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
--------------------------------------------------------
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [56]:
# 创建数组：eye()

print(np.eye(5))
# 创建一个正方的N*N的单位矩阵，对角线值为1，其余为0

print(np.eye(10,k=2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
'''
【课程1.3】  Numpy通用函数

基本操作

'''

In [27]:
# 数组形状：.T/.reshape()/.resize()

import numpy as np

ar1 = np.arange(10)
ar2 = np.zeros((2,5))

print(ar1)
print(ar2)
print(ar1.T)
print(ar2.T)
# .T方法：转置，例如原shape为(3,4)/(2,3,4)，转置结果为(4,3)/(4,3,2) → 所以一维数组转置后结果不变

print('-----------------------------------------------------')

print(ar1.reshape(5,2))
ar3 = np.arange(16)
print(ar3)
print(ar3.reshape(2,8))
print(ar3.reshape(4,4))
print(np.ones((10,10),dtype=int).reshape(4,25))
print(np.reshape(np.arange(16,dtype=int),(8,2)))
# numpy.reshape(a, newshape, order='C')：为数组提供新形状，而不更改其数据，所以元素数量需要一致！！

print('-----------------------------------------------------')

print(np.resize(np.arange(12),(2,6)))
print(np.resize(np.arange(14),(2,8)))
print(np.resize(np.arange(16),(2,6)))
# numpy.resize(a, new_shape)：返回具有指定形状的新数组，如有必要可重复填充所需数量的元素。

# 由上面可知， numpy.reshape（）素数量需要一致；但numpy.resize（）不要求元素数量，少了填充，多了自动排序
# 注意了：.T/.reshape()/.resize()都是生成新的数组！！！

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
-----------------------------------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
-----------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13  0  1]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [36]:
# 数组的复制

ar4 = np.arange(10)
ar5 = ar4
print(ar4)
print(ar5)
print('---------------------------------')
print(ar4 is ar5)
ar4[2] = 22
print(ar4)
print(ar5)
print('---------------------------------')

ar6 = ar4.copy()
ar4[5] = 126
print(ar4)
print(ar5)
print(ar6)
print('---------------------------------')

s = np.arange(10)
print(s)
print(np.resize(s,(2,6)))
print(s.resize(2,6))
print(s)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
---------------------------------
True
[ 0  1 22  3  4  5  6  7  8  9]
[ 0  1 22  3  4  5  6  7  8  9]
---------------------------------
[  0   1  22   3   4 126   6   7   8   9]
[  0   1  22   3   4 126   6   7   8   9]
[ 0  1 22  3  4  5  6  7  8  9]
---------------------------------
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
None
[[0 1 2 3 4 5]
 [6 7 8 9 0 0]]


In [39]:
# 数组类型转换：.astype()

ar7 = np.arange(10,dtype=float)
ar8 = ar7.astype(np.int64)   # 转换数组类型
print(ar7,ar7.dtype)
print(ar8,ar8.dtype)

# a.astype()：转换数组类型
# 注意：养成好习惯，数组类型用np.int32，而不是直接int32

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [10]:
# 数组堆叠

import numpy as np

a = np.arange(5)
b = np.arange(5,9)
print(a)
print(b)
print(np.hstack((a,b)))   # np.hstack() 横向连接
print('------------------')

a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c']])
print(a)
print(b)
print('--------')
print(np.hstack((a,b)))   # np.hstack() 横向连接
print('--------')
print(np.vstack((a,b)))   # np.vstack() 纵向连接
print('------------------')

a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)
print(np.vstack((a,b)))
print('--------')
print(np.stack((a,b),axis=0))   # axis=0表示纵向连接
print('--------')
print(np.stack((a,b),axis=1))   # axis=1表示横向连接

[0 1 2 3 4]
[5 6 7 8]
[0 1 2 3 4 5 6 7 8]
------------------
[[1]
 [2]
 [3]]
[['a']
 ['b']
 ['c']]
--------
[['1' 'a']
 ['2' 'b']
 ['3' 'c']]
--------
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']]
------------------
[0 1 2 3 4]
[5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
--------
[[0 1 2 3 4]
 [5 6 7 8 9]]
--------
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [20]:
# 数组拆分   np.hsplit/np.vsplit

ar = np.arange(16).reshape(4,4)
print(ar)
print('------------------')
print(np.hsplit(ar,2))
print(np.hsplit(ar,4))
print(np.hsplit(ar,4)[3])
print('--------')
print(np.vsplit(ar,2))
print(np.vsplit(ar,4))
print(np.vsplit(ar,4)[3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[[ 3]
 [ 7]
 [11]
 [15]]
--------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[[12 13 14 15]]


In [22]:
# 数组简单运算

ar = np.arange(6).reshape(2,3)
print(ar)
print('------------------')
print(ar + 10)   # 加法
print('--------')
print(ar * 2)   # 乘法
print('--------')
print(1 / (ar+1))  # 除法
print('--------')
print(ar ** 0.5)  # 幂
# 与标量的运算
print('--------')

print(ar.mean())  # 求平均值
print(ar.max())  # 求最大值
print(ar.min())  # 求最小值
print(ar.std())  # 求标准差
print(ar.var())  # 求方差
print(ar.sum(), np.sum(ar,axis = 0))  # 求和，np.sum() → axis为0，按列求和；axis为1，按行求和
print(np.sort(np.array([1,4,3,2,5,6])))  # 排序
# 常用函数

[[0 1 2]
 [3 4 5]]
------------------
[[10 11 12]
 [13 14 15]]
--------
[[ 0  2  4]
 [ 6  8 10]]
--------
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
--------
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
--------
2.5
5
0
1.707825127659933
2.9166666666666665
15 [3 5 7]
[1 2 3 4 5 6]


In [ ]:
'''
【课程1.4】  Numpy索引及切片

核心：基本索引及切片 / 布尔型索引及切片

'''