In [ ]:
'''
【课程1.2  Numpy基础数据结构】 课程作业

'''

In [12]:
import numpy as np

a1 = np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(a1)
print('a1的shape为：',a1.shape)
print('-'*30)

a2 = np.array([['0','1','2','3','4','5'],
              ['a','b','c','d','e','f'],
              ['True', False, True, False, True, True]])
print(a2)
print('a2的shape为：',a2.shape)
print('-'*30)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}]
a1的shape为： (6,)
------------------------------
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'True']]
a2的shape为： (3, 6)
------------------------------


In [15]:
a3 = np.arange(5,15)
print(a3)

[ 5  6  7  8  9 10 11 12 13 14]


In [20]:
a4 = np.zeros((4,4))
print(a4)
print('-'*30)

print(np.ones((2,3)))
print('-'*30)

print(np.eye(3,dtype='int'))
print('-'*30)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
------------------------------
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
------------------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------------------


In [ ]:
'''
【课程1.3  Numpy通用函数】 课程作业

'''

In [1]:
import numpy as np

ar = np.arange(20)
print(ar.reshape(4,5))
print(np.resize(ar,(5,6)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [2]:
ar = np.arange(16).reshape(4,4)
print(ar.astype(np.str))

[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [14]:
ar = np.arange(16).reshape(4,4)
print('创建的数组为：\n', ar, '\n-----------------------')
result = ar * 10 + 100
print('计算后的数组为：\n', result, '\n-----------------------')
print('result的均值为：\n', result.mean(), '\n-----------------------')
print('result求和为：\n', result.sum(), '\n-----------------------')

创建的数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
-----------------------
计算后的数组为：
 [[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]] 
-----------------------
result的均值为：
 175.0 
-----------------------
result求和为：
 2800 
-----------------------


In [ ]:
'''
【课程1.4  Numpy索引及切片】 课程作业

'''

In [1]:
import numpy as np

ar = np.arange(25).reshape(5,5)
print(ar, '\n-------------------')
print(ar[4], '\n-------------------')
print(ar[:2,3:], '\n-------------------')
print(ar[3][2], '\n-------------------')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
-------------------
[20 21 22 23 24] 
-------------------
[[3 4]
 [8 9]] 
-------------------
17 
-------------------


In [2]:
ar = np.arange(10).reshape(2,5)
print(ar, '\n-------------------')
print(ar > 5, '\n-------------------')
print(ar[ar > 5], '\n-------------------')

[[0 1 2 3 4]
 [5 6 7 8 9]] 
-------------------
[[False False False False False]
 [False  True  True  True  True]] 
-------------------
[6 7 8 9] 
-------------------


In [ ]:
'''
【课程1.5  Numpy随机数】 课程作业

'''

In [3]:
ar = np.arange(25, dtype=np.float32).reshape(5,5)
print(ar, '\n----------------------------------------')
print(ar[:2,:2],'\n----------------------------------------')
ar[:2,:2] = np.random.rand(2,2)
print(ar)

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]] 
----------------------------------------
[[ 0.  1.]
 [ 5.  6.]] 
----------------------------------------
[[  0.35338187   0.80105793   2.           3.           4.        ]
 [  0.77916789   0.07682768   7.           8.           9.        ]
 [ 10.          11.          12.          13.          14.        ]
 [ 15.          16.          17.          18.          19.        ]
 [ 20.          21.          22.          23.          24.        ]]


In [6]:
ar1 = np.random.normal(size=(2,5))
print(ar1, '\n----------')
ar2 = np.random.normal(size=(2,5))
print(ar2)
print('----------------------------------------------------------------')

ar = np.vstack((ar1,ar2))
print(ar)

[[ 1.13522262 -1.05931208 -0.08325479 -0.30043113  1.39634175]
 [-0.98366911  0.32735806 -2.13748073 -0.83325262 -0.48295951]] 
----------
[[ 1.23726405  1.50331417  0.55639921 -0.20674422 -0.10489313]
 [-1.16632419  0.47194029  0.24338395 -2.18121986 -0.47223832]]
----------------------------------------------------------------
[[ 1.13522262 -1.05931208 -0.08325479 -0.30043113  1.39634175]
 [-0.98366911  0.32735806 -2.13748073 -0.83325262 -0.48295951]
 [ 1.23726405  1.50331417  0.55639921 -0.20674422 -0.10489313]
 [-1.16632419  0.47194029  0.24338395 -2.18121986 -0.47223832]]


In [ ]:
'''
【课程1.6  Numpy数据的输入输出】 课程作业

'''

In [9]:
import os
os.chdir('G:\Python学习\Python-DataAnalysis')

ar = np.random.randint(100, size=(10,10))
print(ar, '\n----------------------------------------------')
np.savetxt('homework.txt', ar, delimiter=',', fmt='%i')
print('finished!')

[[33 60 24 94 45 25 80 76 56 25]
 [24 30 30 99 80  4 96 18 35 36]
 [ 9 43 88 91 95 86 89 59 35 60]
 [94 96 69  4 88  8 45 54 25 80]
 [81 17 76 13 32 42 48 20 87 18]
 [76 91 51 75 80 45 40  3 58 47]
 [72 97 49 53 97 17 37 73 17 28]
 [66 47 36 61 67 82 33 73 23 80]
 [79  8 78 64 40 44 10 18 44 26]
 [95 90 21 31 86 54 26  4 88 86]] 
----------------------------------------------
finished!
