In [ ]:
'''
【课程1.2】  Numpy基础数据结构

NumPy数组是一个多维数组对象，称为ndarray。其由两部分组成：
① 实际的数据
② 描述这些数据的元数据

'''

In [14]:
import numpy as np

ar = np.array([[1,2,3,4,5,6],[22,33,44,55,66,88]])
print([1,2,3,4,5,6])
print(ar,type(ar))
print(ar.ndim)   # 轴数
print(ar.shape)   # 数组的维度，对于n行m列的数组，shape为（n，m），这里是2行6列
print(ar.size)   # 元素的个数
print(type(ar),ar.dtype)
print(ar.itemsize)
print(ar.data)
print('-'*30)
print(ar)
ar

[1, 2, 3, 4, 5, 6]
[[ 1  2  3  4  5  6]
 [22 33 44 55 66 88]] <class 'numpy.ndarray'>
2
(2, 6)
12
<class 'numpy.ndarray'> int32
4
------------------------------
[[ 1  2  3  4  5  6]
 [22 33 44 55 66 88]]


array([[ 1,  2,  3,  4,  5,  6],
       [22, 33, 44, 55, 66, 88]])

In [33]:
# 创建数组

ar1 = np.array(range(10))
ar2 = np.arange(10)
ar3 = np.array([1,2,3,4,5,6])
ar4 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
ar5 = np.array([[1,2,3,4,5],['a','b','c','d','e','f']])
print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(ar5,ar5.ndim)

print(np.random.rand(10).reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6]
[[1 2 3 4 5]
 [2 3 4 5 6]]
[list([1, 2, 3, 4, 5]) list(['a', 'b', 'c', 'd', 'e', 'f'])] 1
[[ 0.52840934  0.14935172  0.51515262  0.7890446   0.68463136]
 [ 0.11247778  0.96305012  0.53876424  0.40503411  0.92404501]]


In [35]:
# 创建数组：arange()，类似range()，在给定间隔内返回均匀间隔的值。

print(np.arange(10))    # 返回0-9，整型
print(np.arange(10.0))  # 返回0.0-9.0，浮点型
print(np.arange(5,12))  # 返回5-11   取值：“前闭后开”的区间
print(np.arange(5.0,12,2))  # 返回5.0-12.0，步长为2
print(np.arange(10000))  # 如果数组太大而无法打印，NumPy会自动跳过数组的中心部分，并只打印边角：

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 5  6  7  8  9 10 11]
[  5.   7.   9.  11.]
[   0    1    2 ..., 9997 9998 9999]


In [48]:
# 创建数组：linspace():返回在间隔[开始，停止]上计算的num个均匀间隔的样本。

print(np.linspace(10,20,num = 20))
print('-'*80)
print(np.linspace(10,20,num = 21))
print('-'*80)
print(np.linspace(10,20,num = 21, endpoint=False))
print('-'*80)
s = np.linspace(10,20,num = 21, retstep = True)
print(s)
print(type(s))
print(s[0])

[ 10.          10.52631579  11.05263158  11.57894737  12.10526316
  12.63157895  13.15789474  13.68421053  14.21052632  14.73684211
  15.26315789  15.78947368  16.31578947  16.84210526  17.36842105
  17.89473684  18.42105263  18.94736842  19.47368421  20.        ]
--------------------------------------------------------------------------------
[ 10.   10.5  11.   11.5  12.   12.5  13.   13.5  14.   14.5  15.   15.5
  16.   16.5  17.   17.5  18.   18.5  19.   19.5  20. ]
--------------------------------------------------------------------------------
[ 10.          10.47619048  10.95238095  11.42857143  11.9047619
  12.38095238  12.85714286  13.33333333  13.80952381  14.28571429
  14.76190476  15.23809524  15.71428571  16.19047619  16.66666667
  17.14285714  17.61904762  18.0952381   18.57142857  19.04761905
  19.52380952]
--------------------------------------------------------------------------------
(array([ 10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
        14.5, 

In [61]:
# 创建数组：zeros()/zeros_like()/ones()/ones_like()

print(np.zeros(10))
print(np.zeros((3,6)))
print(np.zeros((3,6), dtype=np.int))
print('-'*80)

ar = np.array([list(range(10)),list(range(10,20))])
print(ar)

print(np.zeros_like(ar))
print('-'*80)

ar5 = np.ones(9)   #用1来填充
ar6 = np.ones((2,3,4))
ar7 = np.ones_like(ar5)
print(ar5)
print(ar6)
print(ar7)
# ones()/ones_like()和zeros()/zeros_like()一样，只是填充为1

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
--------------------------------------------------------------------------------
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [62]:
# 创建数组：eye()

print(np.eye(5))
# 创建一个正方的N*N的单位矩阵，对角线值为1，其余为0

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
