In [ ]:
'''
【课程1.2  Numpy基础数据结构】 课程作业

'''

In [12]:
import numpy as np

a1 = np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(a1)
print('a1的shape为：',a1.shape)
print('-'*30)

a2 = np.array([['0','1','2','3','4','5'],
              ['a','b','c','d','e','f'],
              ['True', False, True, False, True, True]])
print(a2)
print('a2的shape为：',a2.shape)
print('-'*30)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}]
a1的shape为： (6,)
------------------------------
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'True']]
a2的shape为： (3, 6)
------------------------------


In [15]:
a3 = np.arange(5,15)
print(a3)

[ 5  6  7  8  9 10 11 12 13 14]


In [20]:
a4 = np.zeros((4,4))
print(a4)
print('-'*30)

print(np.ones((2,3)))
print('-'*30)

print(np.eye(3,dtype='int'))
print('-'*30)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
------------------------------
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
------------------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------------------


In [ ]:
'''
【课程1.3  Numpy通用函数】 课程作业

'''

In [2]:
import numpy as np

ar = np.arange(20)
print(ar.reshape(4,5))
print(np.resize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
'''
【课程1.4  Numpy索引及切片】 课程作业

'''

In [ ]:
'''
【课程1.5  Numpy随机数】 课程作业

'''

In [ ]:
'''
【课程1.6  Numpy数据的输入输出】 课程作业

'''